### ISSUE TITLE
SHADOW_DRIVE_1 not passed to exec script

### ISSUE THREAD

**Issue by hafedh-trimeche** [albertony/vss#1]
Hello,
Thank you for this valuable Tool.

**SHADOW_DRIVE_1** not passed to **vss-exec.cmd**
```
...
ECHO SHADOW_DRIVE_1 = %SHADOW_DRIVE_1%
...
```
using this command:
`ShadowRun -mount -exec=vss-exec.cmd %SOURCE_DRIVE%:`

So, this one is used instead (fixing the Drive Name beforehand).
ShadowRun -mount -drive=%VSSDRIVE% -exec=vss-exec.cmd **%SOURCE_DRIVE%:**

Please how to recover the SHADOW_DRIVE_1 inside an execution script?

**Comment by albertony** [comment]
Glad to hear someone found it useful!

Its been a while since I have been working on this, so I may need some time to catch up... But first: Have you tried the [-env](https://github.com/albertony/vss/tree/master/shadowrun#setting-process-environment-variables) option?

**Comment by hafedh-trimeche** [comment]
Thank you for your prompt response.

That was the trick: adding **-env** option.

Best regards
