### ISSUE TITLE
%SHADOW_DRIVE_1% not being replaced

### ISSUE THREAD

**Issue by thuna-garry** [albertony/vss#3]
Perfect utility!  Will also be using it for backups with rsync and my own differential/deduped backup utils.  Thanks for not only the utility, but also the very complete documentation you provided.

Having an issue where it looks like the %SHADOW_DRIVE_1% is not being replaced for the -exec'd command.

Does not work  ("The system cannot find the path specified")...

    ShadowRun.exe -env -mount -exec=C:\Windows\notepad.exe c: -- %SHADOW_DRIVE_1%\backupToT3.sh

nor

    ShadowRun.exe -env -mount -drive=y -exec=C:\Windows\notepad.exe c: -- %SHADOW_DRIVE_1%\backupToT3.sh

Works when drive letter is explicitly provided....

    ShadowRun.exe -env -mount -drive=y -exec=C:\Windows\notepad.exe c: -- y:\backupToT3.sh

If relevant the test machine is:
- Windows 10 Home  
- Version: 21H2
- Build: 19044.2251

**Comment by albertony** [comment]
Thanks for the kind words.. 😊 

Interesting issue... I'm able to reproduce it. It seems to not actually be a problem with setting of the SHADOW_DRIVE_1 variable, nor supplying it to the executed process, but rather notepad not being able to interpret it for some reason. Can't really explain why, off the top of my head. You'll should see that if you try to "route" it through cmd - it will work:

```
ShadowRun.exe -env -mount -exec=C:\Windows\System32\cmd.exe c: -- /C C:\Windows\System32\notepad.exe %SHADOW_DRIVE_1%\backupToT3.sh
```

**Comment by thuna-garry** [comment]
Hmm.  Maybe it has something to do with the windows interpreter,  I don't really know.

FWIW when I try it with directly with my own backup utils I get the same un-expanded issue as with the notepad example, but if I run it under a sub-"cmd" shell as per your example it does work as expected.
  
For myself, it isn't a big issue because I can easily run it in a sub-"cmd",  Honestly I could also just use the --drive option that you've added as the number of machines I'll be using it only a few dozen and consumed drive letters are well known.  But using the environment variable is a little more convenient as the backup scripts/commands can be centrally managed and then available drive letters are auto allocated at run-time on the target server.

In any case I've got a method that works and really want to thank you again for this utility.

**Comment by jwinett** [comment]
The %EnvVariable% replacement done in CMD and Explorer is an optional thing that API callers can request of Win32, I think.  You could use CMD.EXE to echo the whole line before executing it via another system process launcher like this.  Oh, that's essentially @albertony 's solution above.

Again: a zillion thanks for this repository

**Comment by albertony** [comment]
Yes, I think @jwinett hit the nail on the head. The ShadowRun application starts the command given by `--exec`, with any arguments, using the `CreateProcess` API call. This by itself does *not* expand environment variable references. Neither does `notepad` on command line arguments supplied to it, obviously. What could be done is to make ShadowRun call the API function `ExpandEnvironmentStrings` on arguments before supplying them to the `CreateProcess` call (probably protected by a command line argument, e.g. `-expand`) . I will see if I'm able to implement this without too much effort...

**Comment by albertony** [comment]
Maybe it should be the default behaviour - to pass arguments through ExpandEnvironmentStrings? I think maybe that gives the most expected results, least surprises. Then I will add an option to turn it off, instead. This is the same as is done for quoting, where there is `-nq` to disable. Think I will add an alias `-no-quote` to complete the existing `-nq`, and then add `-ne` and `-no-expand` for this new feature.

**Comment by thuna-garry** [comment]
Sounds perfect.  1 up-vote here.

**Comment by albertony** [comment]
Please test it on the latest release: https://github.com/albertony/vss/releases. 🤞

**Comment by thuna-garry** [comment]
Tested basic case... worked perfectly
Tested same with forced drive letter (-drive=y)... worked perfectly
Did not test the -ne / --no-expand option.

Absolutely perfect.  Thank-you again.
